bot:
  #This enables any feature that involves discord syncing.
  enabled: false
  key: ""
mysql:
  enabled: false
  host: ""
  port: 3306
  database: ""
  username: ""
  password: ""
mongodb:
  enabled: false
  host: ""
  port: 3306
  database: ""
location-change:
  #if set to false, verification will take place through the server.
  use-discord: true
2fa:
  #must be DISCORD or GOOGLE
  type: "DISCORD"
sync:
  message:
    - "&eTo sync your account, please follow the following steps:"
    - ""
    - " &61. &eJoin our discord: discord.example.net"
    - " &62. &eEnter the channel #sync-account and send the code &6{code}"
    - " &63. &eSuccess! If everything went right your account is now synced!"
    - ""